CREATE TABLE IF NOT EXISTS RESULT_SHEET (
	USER_ID	INTEGER	NOT NULL,
    X   FLOAT,
    Y   FLOAT,
    R   FLOAT,
    INCLUDED  BOOLEAN
);
CREATE TABLE IF NOT EXISTS USERS (
	ID	INTEGER	PRIMARY KEY,
    NICKNAME	VARCHAR	NOT NULL
);