CREATE TABLE IF NOT EXISTS RESULT_SHEET (
	USER_ID	INT	NOT NULL,
    X   FLOAT,
    Y   FLOAT,
    R   FLOAT,
    INCLUDED  BOOLEAN
);
CREATE TABLE IF NOT EXISTS USERS (
	ID	INT	PRIMARY KEY,
    NICKNAME	VARCHAR	NOT NULL
);